### PR TITLE
Added Russian localization

### PR DESCRIPTION
**Pull request by RazzSG**
If you add our translation to the mod, we will appreciate it and will update as mod is updated.

### CODE REVIEW

**Comment by direwolf420** [comment]
We will rework the codebase slightly to make adding localization 5 times easier in the near future, stay tuned

**Comment by RazzSG** [comment]
That's good to hear

**Comment by direwolf420** [comment]
#12 Adds .lang files, that's all you have to edit and PR later. You can start working on it now if you want and PR when this PR is merged:
https://github.com/direwolf420/ClickerClass/blob/lang_support/Localization/ru-RU.lang
Translation instructions here: https://github.com/direwolf420/ClickerClass/blob/lang_support/README.md

**Comment by direwolf420** [comment]
the PR is merged, you can do your own one now

**Pull request closed without merging**
